import type { Prisma } from "@prisma/client";

export const candidateProfileSelect = {
  id: true,
  name: true,
  email: true,
  phone: true,
  resumeLink: true,
  avatarUrl: true,
  position: true,
  coverLetter: true,
  englishLevel: true,
  chineseLevel: true,
  expectedSalary: true,
  salaryCurrency: true,
  applicationSource: true,
  score: true,
  isNew: true,
  createdAt: true,
  jobId: true,
  stageId: true,
  recruiterId: true,
  location: true,
  telegram: true,
  offerLink: true,
  firstContactDate: true,
  lastContactDate: true,
  stage: { select: { id: true, name: true } },
  job: { select: { id: true, title: true } },
  recruiter: { select: { id: true, name: true, email: true, image: true } },
  tagAssignments: {
    select: {
      tag: { select: { id: true, name: true, color: true } },
    },
  },
  applications: {
    select: {
      id: true,
      candidateId: true,
      jobId: true,
      stageId: true,
      createdAt: true,
      job: { select: { id: true, title: true, status: true } },
      stage: { select: { id: true, name: true } },
    },
    orderBy: { createdAt: "desc" as const },
  },
  candidateNotes: {
    select: {
      id: true,
      content: true,
      candidateId: true,
      authorId: true,
      authorName: true,
      authorRole: true,
      authorPhotoUrl: true,
      createdAt: true,
    },
    orderBy: { createdAt: "desc" as const },
  },
  interviews: {
    select: {
      id: true,
      candidateId: true,
      title: true,
      status: true,
      scheduledAt: true,
      type: true,
      durationMinutes: true,
      messageBody: true,
      meetLink: true,
      createdAt: true,
      updatedAt: true,
    },
    orderBy: { scheduledAt: "desc" as const },
  },
  emailMessages: {
    select: {
      id: true,
      candidateId: true,
      interviewId: true,
      direction: true,
      status: true,
      senderName: true,
      senderEmail: true,
      recipientName: true,
      recipientEmail: true,
      ccEmails: true,
      subject: true,
      body: true,
      isRead: true,
      isClicked: true,
      openedAt: true,
      clickedAt: true,
      sentAt: true,
      createdAt: true,
    },
    orderBy: { sentAt: "desc" as const },
  },
  testAssignments: {
    select: {
      id: true,
      candidateId: true,
      templateId: true,
      sentByName: true,
      status: true,
      gmailMessageId: true,
      sentAt: true,
      createdAt: true,
      template: { select: { id: true, title: true, fileName: true } },
    },
    orderBy: { createdAt: "desc" as const },
  },
  documents: {
    select: {
      id: true,
      candidateId: true,
      category: true,
      title: true,
      fileName: true,
      mimeType: true,
      fileSize: true,
      uploadedByName: true,
      createdAt: true,
    },
    orderBy: { createdAt: "desc" as const },
  },
  customFieldValues: {
    select: { fieldKey: true, value: true },
  },
  links: {
    select: {
      id: true,
      label: true,
      url: true,
      createdAt: true,
      updatedAt: true,
    },
    orderBy: { createdAt: "asc" as const },
  },
} satisfies Prisma.CandidateSelect;

export type CandidateProfileRecord = Prisma.CandidateGetPayload<{
  select: typeof candidateProfileSelect;
}>;
